export const screenSize = {
    mobileS: "320px",
    mobileSM: "360px",
    mobileM: "412px",
    mobileMM: "430px",
    mobileL: "575px",
    mobileXL: "576px",
    tablet: "768px",
    tabletM: "1024px",
    belowTablet: "767px",
    laptopM: "992px",
    laptopL: "1200px",
    desktop: "1440px",
    desktopL: "2560px",
};

const Device = {
    mobileS: `@media screen and (min-width: ${screenSize.mobileS})`,
    mobileMaxS: `@media screen and (max-width: ${screenSize.mobileS})`,
    mobileMinSM: `@media screen and (min-width: ${screenSize.mobileSM})`,
    mobileMaxSM: `@media screen and (max-width: ${screenSize.mobileSM})`,
    mobileM: `@media screen and (min-width: ${screenSize.mobileM})`,
    mobileMaxSceen: `@media screen and (max-width: ${screenSize.mobileM})`,
    mobileMM: `@media screen and (min-width: ${screenSize.mobileMM})`,
    mobileMMaxSceen: `@media screen and (max-width: ${screenSize.mobileMM})`,
    mobileL: `@media screen and (max-width: ${screenSize.mobileL})`,
    mobileLMin: `@media screen and (min-width: ${screenSize.mobileL})`,
    tablet: `@media screen and (min-width: ${screenSize.tablet})`,
    tabletMax: `@media screen and (max-width: ${screenSize.tabletM})`,
    laptopM: `@media screen and (min-width: ${screenSize.laptopM})`,
    laptopMax: `@media screen and (max-width: ${screenSize.laptopM})`,
    laptopL: `@media screen and (min-width: ${screenSize.laptopL})`,
    laptopLMax: `@media screen and (max-width: ${screenSize.laptopL})`,
    desktop: `@media screen and (min-width: ${screenSize.desktop})`,
    desktopL: `@media screen and (min-width: ${screenSize.desktopL})`,
    mobileLtomobileS: `@media screen and (max-width: ${screenSize.mobileL}) and (min-width: ${screenSize.mobileS}) `,
    mobileLtobelowTablet: `@media screen and (min-width: ${screenSize.mobileXL}) and (max-width: ${screenSize.belowTablet})`,
    tabletMTL: `@media screen and (min-width: ${screenSize.tablet}) and (max-width: ${screenSize.laptopM})`,
    tabletMTLS: `@media screen and (min-width: ${screenSize.tablet}) and (max-width: ${screenSize.laptopL})`,
    laptopML: `@media screen and (min-width: ${screenSize.laptopM}) and (max-width: ${screenSize.laptopL})`,
    tabletML: `@media screen and (min-width: ${screenSize.tablet}) and (max-width: ${screenSize.tabletM})`,
};

export default Device;
