import { Color, FontWeight } from "../../Constants";

const Slider = {
  wrap_pos: "relative",
  btn_wrap_pos: "absolute",
  btn_wrap_bottom: "20px",
  btn_wrap_textAlign: "center",
  btn_wrap_width: "100%",
  btn_wrap_dis: "none",

  slide_div_mg: "0 5px",
  slide_div_mg_tab: "0 10px",
  slide_active_btn_dis: "block",
  img_cont_bg: Color.white,
  slick_dot_bottom: "unset",
  active_slide_btn_before_opacity: 1,
  active_slide_btn_before_fs: "1.2rem",
  active_slide_btn_before_clr: Color.white,
  slide_btn_before_fs: "1rem",
  slide_btn_before_clr: Color.black,
  slide_btn_before_opacity: 1,
  slide_pd_top: "40px 0 0",
  slide_pd_bottom: "0 0 40px",
  slider_pd: "40px 0 40px",
  slider_dot_top: 0,
  slick_arrow_trans: "unset",
  slick_next_right: 0,
  slick_prev_left: 0,
  arrow_top: 0,
  bottom_arrow_top: "unset",
  bottom_arrow_bottom: 0,
  arrow_zIndex: 2,
  slick_arrow_before_opacity: 1,
  slick_arrow_before_clr: Color.white,
  slick_arrow_clr: Color.white,
  custom_arrow_content: "none",

  badge_pos: "absolute",
  badge_bottom: 0,
  badge_right: "10px",
  badge_bg: Color.black,
  badge_bdrRds: "6px 6px 0px 0px",
  badge_pd: "4px 8px",
  badge_fs: "1.2rem",
  badge_ln: "1.2rem",
  badge_fntWg: FontWeight.weightHeavy,
  badge_clr: Color.black,
  badge_span_clr: Color.white,
  badge_span_pd: "0 3px",
  badge_span_trans: "translateY(-1px)",
  badge_span_dis: "inline-block",

  testi_dots_top: "unset",
  testi_dots_bottom: "75px",
  testi_dots_li_mg: "0",
  test_cont_dis: "flex",
  testi_cont_fDir: "column-reverse",
  testi_cont_pd: "40px 0 0",
  testi_cont_gap: "95px",
  test_cont_fDir_tab: "row",
  test_cont_pd_tab: "10px 0 0",
  testi_cont_gap_tab: 0,
  testi_profile_mg: "auto",

  testi_profile_width: "40%",
  testi_profile_minH: "435px",
  testi_profile_dis: "flex",
  testi_profile_jContent: "center",
  test_profile_aItems: "flex-end",
  testi_arrow_top: "50%",
  testi_arrow_height: "50px",
  testi_arrow_width: "50px",
  testi_arrow_bg: Color.black,
  testi_arrow_bdrRds: "50%",
  testi_arrow_clr: Color.white,

  quote_bgsize: "40%",
  quote_bgsize_tab: "auto",
  quote_bg_pos: "30% 0",
  review_width: "60%",

  review_fstyle: "italic",
  review_pd: "0 0 20px",
  review_textAlign: "left",
  review_dis: "flex",
  review_minH: "180px",
  review_pd_tab: "0 0 40px",
  review_aItems: "flex-end",

  info_dis: "flex",
  info_gap: "10px 15px",
  info_fWrap: "wrap",
  info_textAlign: "center",
  info_aItems: "baseline",
  info_jContent: "center",
  info_jContent_tab: "flex-start",
  info_textAlign_tab: "left",
  uname_width: "100%",
  uname_width_tab: "32%",

  card_wrap_dis: "flex",
  card_wrap_aItems: "center",
  card_wrap_jContent: "center",
  card_wrap_fDir: "column",
  card_wrap_gap: "24px",
  card_wrap_fDir_tab: "row",

  card_cont_bg: Color.white,
  card_cont_pd: "30px",
  card_cont_minH: "300px",
  card_cont_bdrRds: "30px",
  card_cont_width: " 100%",
  card_cont_width_tab: "41%",
  card_header_minH: "96px",
  card_header_fs: "1.4rem",
  card_header_ln: "2rem",
  card_header_fntWg: FontWeight.weightBold,
  card_header_mg: "10px 0 0",
  card_time_mg: 0,
  card_time_fntWg: FontWeight.weightNormal,
  card_review_minH: "46px",
  card_content_fntWg: FontWeight.weightBold,
  card_comment_fs: "1.6rem",
  card_comment_ln: "2.4rem",
  card_comment_clr: Color.black,
  card_comment_fntWg: FontWeight.weightNormal,

  social_dis: "flex",
  social_fWrap: "wrap",
  social_wrap_width: "100%",
  social_wrap_dis: "flex",
  social_wrap_jContent: "center",
  social_wrap_fDir: "column",
  social_wrap_aItems: "center",
  social_wrap_gap: "30px",
  social_wrap_aItems_tab: "flex-start",
  social_wrap_width_tab: "45%",
  dynamic_content_dis: "flex",
  dynamic_content_gap: "30px",
  social_img_mg: "10px 0 0",
  social_slider_width: "100%",
  social_slider_width_tab: "55%",
};
export default Slider;
